# renew_before_expiry = 30 days
version = 4.0.0
archive_dir = /etc/letsencrypt/archive/ssuwt-library.ru
cert = /etc/letsencrypt/live/ssuwt-library.ru/cert.pem
privkey = /etc/letsencrypt/live/ssuwt-library.ru/privkey.pem
chain = /etc/letsencrypt/live/ssuwt-library.ru/chain.pem
fullchain = /etc/letsencrypt/live/ssuwt-library.ru/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = a49a938b83c3f5bc567c4ff445ff5149
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
ssuwt-library.ru = /var/www/certbot
